# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='left',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='top',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
